package com.skillsync.notification_service.entity;

public enum NotificationType {
	SESSION_BOOKED,
	SESSION_ACCEPTED,
	SESSION_REJECTED,
	SESSION_CANCELLED,
	SESSION_COMPLETED,
	SESSION_APPROVED,
	USER_REGISTERED,
	MENTOR_APPROVED,
	REMAINDER,
	JOINED,
	LEFT
}
