apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-static-ingress
  namespace: skillsync
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /eureka/$1$2$3
spec:
  ingressClassName: nginx
  rules:
    - host: skillsync.mooo.com
      http:
        paths:
          - path: /eureka/(css)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eureka-server
                port:
                  number: 8761
          - path: /eureka/(js)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eureka-server
                port:
                  number: 8761
          - path: /eureka/(fonts)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eureka-server
                port:
                  number: 8761
