apiVersion: v1
kind: Secret
metadata:
  name: skillsync-secrets
  namespace: skillsync
type: Opaque
data:
  # echo -n "your-value" | base64
  MYSQL_ROOT_PASSWORD: cm9vdA==                         # root
  RABBITMQ_USER: Z3Vlc3Q=                               # guest
  RABBITMQ_PASS: Z3Vlc3Q=                               # guest
  RAZORPAY_KEY_ID: cnpwX3Rlc3RfU1dHVXNJU01KVGs0SUg=    # rzp_test_SWGUsISMJTk4IH
  RAZORPAY_KEY_SECRET: SThrakZwR05JVTJyNGl1VDJqM3h4dHJu # I8krFpGNIU2r4iuT2j3xxtrn
  RESEND_API_KEY: WUVVWF9BUElfS0VZX0hFUkU=              # replace with your real Resend key
