apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: skillsync
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS skillsync_auth;
    CREATE DATABASE IF NOT EXISTS user_service;
    CREATE DATABASE IF NOT EXISTS mentor_service;
    CREATE DATABASE IF NOT EXISTS skill_service;
    CREATE DATABASE IF NOT EXISTS session_service;
    CREATE DATABASE IF NOT EXISTS `group-service`;
    CREATE DATABASE IF NOT EXISTS `reviews-service`;
    CREATE DATABASE IF NOT EXISTS `notification-service`;
    CREATE DATABASE IF NOT EXISTS payment_service;

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: skillsync
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: skillsync
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          args:
            - --binlog-expire-logs-seconds=604800  # auto-purge binlogs after 7 days
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skillsync-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -proot
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-sql
          configMap:
            name: mysql-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: skillsync
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
